app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('<int:pk>/', views.DetailView.as_view(), name='detail'),
  path('<int:item_id>/update/', views.update, name='update'),
]

todo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
  path('app/', include('app.urls')),
  path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

class Item(models.Model):
  item_text = models.CharField(max_length=200)
  complete = models.BooleanField(default=False)

  def __str__(self):
    return self.item_text

app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Item

class IndexView(generic.ListView):
  template_name = 'app/index.html'
  context_object_name = 'item_list'
  def get_queryset(self):
    return Item.objects.all()

class DetailView(generic.DetailView):
  model = Item
  template_name = 'app/detail.html'

def update(request, item_id):
  item = get_object_or_404(Item, pk=item_id)
  if "checkbox" in request.POST:
    item.complete = True
  else:
    item.complete = False
  item.save()
  return HttpResponseRedirect(reverse('app:detail', args=(item.id,)))

app/templates/app/detail.html
<!-- <h1>{{ item.item_text }}</h1>
<p>{{item.complete}}</p>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'app:update' item.id %}" method="post">
{% csrf_token %}
<input type="checkbox" name="checkbox" id="item" {% if item.complete %} checked="checked"{% endif %}>
<label for="checkbox">Completed?</label><br>
<input type="submit" value="Update">
</form> -->

app/templates/app/index.html
<!-- {% if item_list %}
  <ul>
  {% for item in item_list %}
    <li><a href="{% url 'app:detail' item.id %}">{{ item.item_text }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>You have no items.</p>
{% endif %} -->